config/routes.rb
Rails.application.routes.draw do

  resources :admins

  root "welcome#index"
  get    'signup'  => 'members#signup', as:'signup'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'checkout/:id' => 'book_transactions#checkout' , as: "checkout"
  post 'checkout' => 'book_transactions#create1'
  get 'checkin/:id' => 'book_transactions#checkin' , as: "checkin"
  post 'checkin' => 'book_transactions#create2'

  resources :books
  resources :members
  resources :book_transactions

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div style="text-align: center">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/admins/edit.html.erb
<h1 style="text-align: center">Editing Admin</h1>

<%= render 'form' %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center">Admins</h1>

<table align="center"  border="1" width="500">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>

        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Admin', new_admin_path %>-->

app/views/admins/new.html.erb
<h1 style="text-align: center">New Admin</h1>

<%= render 'form' %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <%if current_user.id.eql? @admin.id %>
    <strong>Password:</strong>
  	<%= @admin.password %>
  <%end%>
</p>

<p><%= link_to 'Edit Profile', edit_admin_path(@admin) %></p>
<p><%= link_to 'Logout', logout_path, method: "delete" %><p>