config/routes.rb
Rails.application.routes.draw do

  resources :admins

  root "welcome#index"
  get    'signup'  => 'members#signup', as:'signup'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'checkout/:id' => 'book_transactions#checkout' , as: "checkout"
  post 'checkout' => 'book_transactions#create1'
  get 'checkin/:id' => 'book_transactions#checkin' , as: "checkin"
  post 'checkin' => 'book_transactions#create2'

  resources :books
  resources :members
  resources :book_transactions

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_search.html.erb
<%= form_tag books_path, :method => 'get' do %>

  <div class="form-group">

     <p>Search by</p>
     <%= radio_button_tag(:search_option, "name", checked:true) %>
     <%= label_tag :search_option, "Title" ,class: "search" %>

     <%= radio_button_tag(:search_option, "author") %>
     <%= label_tag :search_option, "Author"  ,class: "search"%>

     <%= radio_button_tag(:search_option, "isbn") %>
     <%= label_tag :search_option, "ISBN" ,class: "search" %>
     <br/><br/>

     <label for="search">Enter search phrase ...</label>
     <%= text_field_tag :search, params[:search] ,class: "search"%>

     <%= submit_tag "Search", :name => nil ,class: "btn-sm btn-primary" %>

   </div>
 <% end %>

app/views/welcome/index.html.erb
<div id="privileges"><%= flash[:privileges] %></div>

<% @title = "Welcome" %>
<%= render "search" %>
<%x = logged_in? %>
<% unless x.nil? %>

<div style="text-align: center">
<h3 style="text-align: center"><%= link_to "View available books", books_path %></h3>
<% if is_admin? %>
       <p><%= link_to 'Add an Admin', new_admin_path %></p>
       <p><%= link_to 'Add a Book', new_book_path %></p>
       <p><%= link_to 'Show all Books', books_path %></p>
       <p><%= link_to 'Show all Admins', admins_path %></p>
       <p><%= link_to 'Show all Members', members_path %></p>
     <%end%>
<%else%>
    <div style="text-align:center" >
    <h3 ><%= link_to "New User? Signup", signup_path %></h3>
	<h3 ><%= link_to "Existing User? Login", login_path %></h3>
    </div>


<%end%>

</div>