config/routes.rb
Rails.application.routes.draw do

  resources :admins

  root "welcome#index"
  get    'signup'  => 'members#signup', as:'signup'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'checkout/:id' => 'book_transactions#checkout' , as: "checkout"
  post 'checkout' => 'book_transactions#create1'
  get 'checkin/:id' => 'book_transactions#checkin' , as: "checkin"
  post 'checkin' => 'book_transactions#create2'

  resources :books
  resources :members
  resources :book_transactions

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :isbn, uniqueness: true
  validates :isbn, numericality: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 200 }
  validates :authors, presence: true, length: { maximum: 100 }
  validates :authors, format: { :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/ }
  has_many :book_transactions
  has_many :ordered_members, -> { order(id: :asc) }, through: :book_transactions, source: :members
  has_many :subscribers
  has_many :members, through: :subscribers
  before_destroy :available?
  def list_of_owners
    members = BookTransaction.where(book_id:id).map{|x| x.member}
  end
  def current_owner
    members = BookTransaction.where(book_id:id).map{|x| x.member}
    if( members.count.odd? )
      current_owner = members.last
    else
      nil
    end
  end
  def available?
    current_owner.nil?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:return,  :show, :edit, :update, :destroy]
  before_action :is_logged_in?



  # GET /books
  # GET /books.json
  def is_logged_in?
    if current_user == nil
      flash[:privileges]="Please log in"
      redirect_to login_path
    end
  end 

  def index
    if params[:search_option].present?
      if (params[:search_option] == "isbn")
        @books = Book.where(isbn: params[:search])
      elsif (params[:search_option] == "author")
        @books = Book.where("authors LIKE '%#{params[:search]}%'")
      else
        # Search by title/name
        @books = Book.where("name LIKE '%#{params[:search]}%'")
      end
    else
      # Show all books
      @books = Book.all
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { redirect_to @books , notice: 'Book was not successfully created.'}
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    if @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to books_path, notice: 'Book can not be removed since it has active checkout'
    end
  end

  def return
    @book.update(status: "Available")
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, notice:"Book not found"
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:isbn, :name, :authors, :description)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div style="text-align: center">
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.number_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :authors %><br>
    <%= f.text_area :authors %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/books/edit.html.erb
<h1 style="text-align: center">Editing Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div style="text-align: center">

<h1 >Books</h1><br>

  <table align="center" style="margin: 0px auto;" border="1" width="500">
  <thead>
    <tr>
      <th>ISBN</th>
      <th>Name</th>
      <th>Authors</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.isbn %> </td>
        <td><%= book.name %></td>
        <td><%= book.authors %></td>
        <td><%= book.status %></td>

        <% if is_admin? %>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>

          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <td><%= link_to 'View Details', book_path(book) %></td>
        <td>
        <%if book.status == "Available" %>

              <%if  is_admin? %>

              <%else%>
                <%= link_to 'Check out', checkout_path(book.id),class: "btn-sm btn-success" %></td>
              <%end%>
        <%else%>
            <%if is_admin? %>

                  <%elsif current_user.books.where(isbn: book.isbn).count.odd? %>
                <%= link_to 'Return Book', checkin_path(book.id), class: "btn-sm btn-warning" %>
            <%end%>
         <%end%>
         </td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/books/new.html.erb
<h1 style="text-align: center">Add New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ISBN:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @book.authors %>
</p>
<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>
<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>

<%if is_admin? and !@book.available?%>
    <p>
      <strong>Currently owned by:</strong>
      <%= @book.current_owner.name %>
    </p>
<%end%>
<%link_to "Check Out" , checkout_path(@book.id) %>

<%= link_to 'Edit', edit_book_path(@book) %> 