config/routes.rb
Rails.application.routes.draw do

  resources :admins

  root "welcome#index"
  get    'signup'  => 'members#signup', as:'signup'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'checkout/:id' => 'book_transactions#checkout' , as: "checkout"
  post 'checkout' => 'book_transactions#create1'
  get 'checkin/:id' => 'book_transactions#checkin' , as: "checkin"
  post 'checkin' => 'book_transactions#create2'

  resources :books
  resources :members
  resources :book_transactions

end

app/models/member.rb
class Member < ActiveRecord::Base
	validates :email, :email_format => { :message => "The email address is not valid or in the wrong format" }
	validates_uniqueness_of :email
	validates :name, presence: true
	validates :password, length: { in: 6..20 }

	has_many :book_transactions
	has_many :books, through: :book_transactions
	before_destroy :active_checkouts?
	def checked_out_books
		checked_out_books = []
		books = BookTransaction.where(member_id:id).map{|x| x.book}
		books.uniq.each do |book|
			if(books.count(book).odd?)
				checked_out_books << book
			end
		end
		checked_out_books
	end
	def active_checkouts?
		checked_out_books.empty?
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :checkauth?, only: :index
  
  def checkauth?
    unless is_admin?
      flash[:privileges]="Not enough privileges"
      redirect_to root_path
    end
  end
  def signup
    @member = Member.new
  end

  def login
  end
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        log_in(@member)
        format.html { redirect_to @member, notice: "Member #{@member.name} was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email, :password)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div style="text-align: center">

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/members/_login.html.erb
<div id="notice" ><%= flash.now[:notice] unless flash.now[:notice].nil? %></p>
<%= form_for(:session, url: login_path) do |f| %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
<% end %>
    </div>

app/views/members/_signup.html.erb
<%= form_for(@member) do |f| %>
    <% if @member.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

          <ul>
            <% @member.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <br><br>
    <div style="text-align: center" class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <br>
    <div style="text-align: center" class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <br>
    <div style="text-align: center" class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <br>

    <div style="text-align: center" class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/members/edit.html.erb
<h1 style="text-align: center">Editing Member</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @member %>-->

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style=text-align:center>Members</h1>

<table align="center" border="1" width="500">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>

        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'signup' %>

app/views/members/show.html.erb
<div style="text-align: center">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @member.password %>
</p>

  <%if @member.checked_out_books.empty? %>
      <p>There are no books checked out.</p>
  <%end%>
  <p>List of books currently checked out</p>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Book Name</th>
    </tr>
    </thead>
    <tbody>
    <% @member.checked_out_books.each do |book| %>
        <tr>
          <td><%= book.name %></td>
          <td><%= link_to 'Show', book, class: "btn-sm btn-primary"%></td>
          <td><%= link_to 'Return Book', checkin_path(book.id) , class: "btn-sm btn-warning"%></td>
        </tr>
    <% end %>
    </tbody>
  </table>

<p><%= link_to 'Edit Profile', edit_member_path(@member)%>
<p><%= link_to 'Logout', logout_path, method: "delete" %><p>
</div>

app/views/members/signup.html.erb
<% content_for :title, "Title for specific page" %>
<div style="text-align: center">
<h1>New Member Sign Up</h1>

  <%= render 'signup' %>
</div>